spring:
  application:
    name: KafkaMicroServices
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydatabase

logging:
  level:
    org.springframework.web: "debug"
    org.hibernate: "error"
