spring:
  application:
    name: NewsConsumer
  kafka:
    bootstrap-servers: localhost:29092
  data:
    redis:
      host: localhost
      port: 6379
      password: root
server:
  port: 9090
#mediastack:
#  uri: http://api.mediastack.com/v1/news
#  api-key: <your-api-key>
#  countries: us
#  limit: 25
newsapi:
  uri: https://api.thenewsapi.com/v1/news/all
  api-key: MvK8sh6IzLmKcI24slriPkzSI5ZRfibIWW5JasgA
  search: usd